defaults: &defaults
  name: rappbase
  secret_token: '1e87b9116f5d5aa97e59ca428647baea9edfe769439ff5ee034b8ab1a39e617ae98fcc117c7a8fcdefa4e89c3b4eaa1507b84b7bb5c33f7f6a81bfe6ac373440'
  header_navs:
    test:
      new: "/tests/new"
      index: "/tests"

development: &unpro_settings
  <<: *defaults
  domain: l.lh

production: &pro_settings
  <<: *defaults
  domain: rappbase.me

test:
  <<: *unpro_settings
